# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude:
  (?x)^(
      .*/migrations/.* |
      .*/__init__.py |
      \.github |
      \.git |
      \.tox
  )$


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # The code checkers for the backend project part
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        exclude: ^frontend/

  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        exclude: ^frontend/

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ^frontend/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        exclude: ^frontend/

  # The code checkers for the frontend project part
