version: "3.9"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python /backend/generator/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./backend/:/backend
    ports:
      - "8000:8000"
    container_name: cv_generator_backend
  db:
    image: postgres
    environment:
      POSTGRES_DB: cv_generator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      timeout: 20s
      retries: 3
    container_name: cv_generator_db
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: