# Generated by Django 3.2.7 on 2021-09-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=255)),
                ('experience', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=150)),
                ('number', models.CharField(max_length=15)),
                ('about_me', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('places_of_work', models.ManyToManyField(to='profile.PlaceOfWork')),
            ],
        ),
    ]
