# Generated by Django 3.2.7 on 2021-09-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('_from', models.DateField()),
                ('to', models.DateField()),
                ('employer', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=150)),
                ('used_technology', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profile.profile')),
            ],
        ),
    ]
