# Generated by Django 3.2.7 on 2021-10-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience',
        ),
        migrations.AddField(
            model_name='experience',
            name='since',
            field=models.DateField(default=1914),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='until',
            field=models.DateField(default=1915),
            preserve_default=False,
        ),
    ]
