# Generated by Django 3.2.7 on 2021-10-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20211013_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
